create extension if not exists pgcrypto;

create table if not exists app_users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  full_name varchar(100) not null,
  email varchar(150) unique not null,
  role varchar(30) default 'admin',
  created_at timestamptz default now()
);

create table if not exists customers (
  id bigint generated by default as identity primary key,
  customer_code varchar(20) unique not null,
  name varchar(100) not null,
  phone varchar(30),
  email varchar(150),
  address text,
  created_at timestamptz default now()
);

create table if not exists suppliers (
  id bigint generated by default as identity primary key,
  supplier_code varchar(20) unique not null,
  name varchar(100) not null,
  phone varchar(30),
  email varchar(150),
  address text,
  created_at timestamptz default now()
);

create table if not exists dress_categories (
  id bigint generated by default as identity primary key,
  category_name varchar(100) unique not null,
  description text
);

create table if not exists expense_categories (
  id bigint generated by default as identity primary key,
  category_name varchar(100) unique not null
);

create table if not exists accounts (
  id bigint generated by default as identity primary key,
  account_code varchar(20) unique not null,
  account_name varchar(100) not null,
  account_type varchar(30) not null check(account_type in('Asset','Liability','Equity','Revenue','Expense'))
);

create table if not exists dresses (
  id bigint generated by default as identity primary key,
  dress_code varchar(20) unique not null,
  name varchar(100) not null,
  category_id bigint references dress_categories(id) on delete set null,
  size varchar(20),
  color varchar(50),
  purchase_price numeric(15,2) default 0 check(purchase_price>=0),
  rental_price numeric(15,2) not null check(rental_price>=0),
  condition varchar(30) default 'Good',
  status varchar(30) default 'Available',
  photo_url text,
  supplier_id bigint references suppliers(id) on delete set null,
  created_at timestamptz default now()
);

create table if not exists rentals (
  id bigint generated by default as identity primary key,
  rental_code varchar(30) unique not null,
  customer_id bigint not null references customers(id),
  rental_date date not null,
  return_due_date date not null,
  total_amount numeric(15,2) default 0,
  deposit_amount numeric(15,2) default 0,
  status varchar(30) default 'Booked',
  created_at timestamptz default now(),
  check(return_due_date>=rental_date)
);

create table if not exists rental_details (
  id bigint generated by default as identity primary key,
  rental_id bigint not null references rentals(id) on delete cascade,
  dress_id bigint not null references dresses(id),
  rental_price numeric(15,2) not null,
  quantity int default 1 check(quantity>0),
  subtotal numeric(15,2) not null
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  payment_code varchar(30) unique not null,
  rental_id bigint references rentals(id) on delete set null,
  payment_date date not null,
  amount numeric(15,2) not null check(amount>0),
  payment_method varchar(30),
  description text,
  created_at timestamptz default now()
);

create table if not exists returns (
  id bigint generated by default as identity primary key,
  rental_id bigint not null references rentals(id),
  return_date date not null,
  condition varchar(30),
  late_days int default 0 check(late_days>=0),
  notes text,
  created_at timestamptz default now()
);

create table if not exists penalties (
  id bigint generated by default as identity primary key,
  return_id bigint references returns(id) on delete cascade,
  penalty_type varchar(50) not null,
  amount numeric(15,2) not null check(amount>=0),
  description text,
  created_at timestamptz default now()
);

create table if not exists purchases (
  id bigint generated by default as identity primary key,
  purchase_code varchar(30) unique not null,
  supplier_id bigint references suppliers(id) on delete set null,
  purchase_date date not null,
  total_amount numeric(15,2) default 0,
  payment_status varchar(30) default 'Unpaid',
  created_at timestamptz default now()
);

create table if not exists purchase_details (
  id bigint generated by default as identity primary key,
  purchase_id bigint not null references purchases(id) on delete cascade,
  dress_id bigint references dresses(id) on delete set null,
  quantity int default 1,
  purchase_price numeric(15,2) not null,
  subtotal numeric(15,2) not null
);

create table if not exists dress_movements (
  id bigint generated by default as identity primary key,
  dress_id bigint not null references dresses(id) on delete cascade,
  movement_type varchar(30) not null,
  reference_id bigint,
  movement_date timestamptz default now(),
  description text
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  expense_code varchar(30) unique not null,
  category_id bigint references expense_categories(id) on delete set null,
  expense_date date not null,
  amount numeric(15,2) not null check(amount>0),
  payment_method varchar(30),
  description text,
  created_at timestamptz default now()
);

create table if not exists journal_entries (
  id bigint generated by default as identity primary key,
  journal_code varchar(30) unique not null,
  journal_date date not null,
  reference_type varchar(50),
  reference_id bigint,
  description text,
  created_at timestamptz default now()
);

create table if not exists journal_details (
  id bigint generated by default as identity primary key,
  journal_id bigint not null references journal_entries(id) on delete cascade,
  account_id bigint not null references accounts(id),
  debit numeric(15,2) default 0,
  credit numeric(15,2) default 0,
  check(not(debit>0 and credit>0)),
  check(debit>0 or credit>0)
);

create index if not exists idx_dresses_status on dresses(status);
create index if not exists idx_rental_details_dress on rental_details(dress_id);
create index if not exists idx_journal_details_account on journal_details(account_id);