-- LAVE security, settings, audit, and single-source inventory migration.
-- Run after 06_integration_fix.sql (and 07-09 when those are part of deployment).

ALTER TABLE dresses
  ADD COLUMN IF NOT EXISTS description text;

ALTER TABLE dresses
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

ALTER TABLE dress_movements
  ADD COLUMN IF NOT EXISTS status_before varchar(30);

ALTER TABLE dress_movements
  ADD COLUMN IF NOT EXISTS status_after varchar(30);

ALTER TABLE dress_movements
  ADD COLUMN IF NOT EXISTS reference_code varchar(30);

ALTER TABLE app_users
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

ALTER TABLE app_users
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE app_users
  DROP CONSTRAINT IF EXISTS app_users_role_check;

ALTER TABLE app_users
  ADD CONSTRAINT app_users_role_check
  CHECK (lower(role) IN ('admin','staff','accounting','owner'));

CREATE TABLE IF NOT EXISTS business_settings(
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  business_name varchar(150) NOT NULL DEFAULT 'LAVE DRESS RENTAL & ACCOUNTING',
  logo_url text,
  address text,
  phone varchar(40),
  email varchar(150),
  website varchar(150),
  tax_number varchar(60),
  description text,
  currency varchar(10) NOT NULL DEFAULT 'IDR',
  currency_symbol varchar(10) NOT NULL DEFAULT 'Rp',
  updated_by uuid REFERENCES auth.users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO business_settings(id)
VALUES (true)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS accounting_settings(
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  accounting_method varchar(30) NOT NULL DEFAULT 'Accrual',
  period_start date,
  period_end date,
  cash_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  receivable_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  inventory_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  payable_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  rental_revenue_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  penalty_revenue_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  expense_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO accounting_settings(id)
VALUES (true)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS document_settings(
  document_type varchar(30) PRIMARY KEY,
  prefix varchar(12) NOT NULL,
  sequence_name varchar(80) NOT NULL UNIQUE,
  updated_by uuid REFERENCES auth.users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO document_settings(document_type,prefix,sequence_name)
VALUES
  ('customer','CUS-','customer_number_seq'),
  ('supplier','SUP-','supplier_number_seq'),
  ('dress','DRS-','dress_number_seq'),
  ('rental','RENT-','rental_number_seq'),
  ('purchase','PUR-','purchase_number_seq'),
  ('payment','PAY-','payment_number_seq'),
  ('return','RET-','return_number_seq'),
  ('penalty','PEN-','penalty_number_seq'),
  ('expense','EXP-','expense_number_seq'),
  ('journal','JRN-','journal_number_seq')
ON CONFLICT (document_type) DO NOTHING;

CREATE TABLE IF NOT EXISTS system_preferences(
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  theme varchar(30) NOT NULL DEFAULT 'light',
  date_format varchar(30) NOT NULL DEFAULT 'id-ID',
  rows_per_page integer NOT NULL DEFAULT 25 CHECK (rows_per_page BETWEEN 5 AND 200),
  confirm_delete boolean NOT NULL DEFAULT true,
  confirm_transaction boolean NOT NULL DEFAULT true,
  dashboard_period varchar(30) NOT NULL DEFAULT 'month',
  updated_by uuid REFERENCES auth.users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO system_preferences(id)
VALUES (true)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS audit_logs(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action varchar(30) NOT NULL,
  module varchar(50) NOT NULL,
  record_id text,
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at
  ON audit_logs(created_at DESC);

CREATE OR REPLACE FUNCTION current_app_role()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT lower(
    coalesce(
      (
        SELECT role
        FROM app_users
        WHERE auth_user_id = auth.uid()
          AND is_active
      ),
      'staff'
    )
  );
$$;

CREATE OR REPLACE FUNCTION write_audit_log(
  p_action text,
  p_module text,
  p_record_id text,
  p_old jsonb DEFAULT NULL,
  p_new jsonb DEFAULT NULL
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  INSERT INTO audit_logs(
    user_id,
    action,
    module,
    record_id,
    old_value,
    new_value
  )
  VALUES(
    auth.uid(),
    p_action,
    p_module,
    p_record_id,
    p_old,
    p_new
  );
$$;

CREATE OR REPLACE FUNCTION audit_dress_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM write_audit_log(
      'CREATE',
      'Dress',
      NEW.id::text,
      NULL,
      to_jsonb(NEW)
    );
  ELSIF TG_OP = 'UPDATE' THEN
    PERFORM write_audit_log(
      'UPDATE',
      'Dress',
      NEW.id::text,
      to_jsonb(OLD),
      to_jsonb(NEW)
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_dress_change ON dresses;

CREATE TRIGGER audit_dress_change
AFTER INSERT OR UPDATE ON dresses
FOR EACH ROW
EXECUTE FUNCTION audit_dress_change();
CREATE OR REPLACE FUNCTION record_dress_movement()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO dress_movements(
      dress_id,
      movement_type,
      status_before,
      status_after,
      description
    )
    VALUES(
      NEW.id,
      'MASTER_CREATE',
      NULL,
      NEW.status,
      'Dress dibuat dari Master Dress'
    );
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO dress_movements(
      dress_id,
      movement_type,
      status_before,
      status_after,
      description
    )
    VALUES(
      NEW.id,
      'STATUS_CHANGE',
      OLD.status,
      NEW.status,
      'Status dress berubah'
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS record_dress_movement ON dresses;

CREATE TRIGGER record_dress_movement
AFTER INSERT OR UPDATE OF status ON dresses
FOR EACH ROW
EXECUTE FUNCTION record_dress_movement();

CREATE OR REPLACE FUNCTION apply_return_dress_status()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_status varchar(30);
BEGIN
  target_status := CASE NEW.condition
    WHEN 'Baik' THEN 'Available'
    WHEN 'Kotor' THEN 'Laundry'
    WHEN 'Rusak Ringan' THEN 'Repair'
    WHEN 'Rusak Berat' THEN 'Not Available'
    ELSE 'Available'
  END;

  UPDATE dresses
  SET status = target_status
  WHERE id IN (
    SELECT dress_id
    FROM rental_details
    WHERE rental_id = NEW.rental_id
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS apply_return_dress_status ON returns;

CREATE TRIGGER apply_return_dress_status
AFTER INSERT ON returns
FOR EACH ROW
EXECUTE FUNCTION apply_return_dress_status();

-- PostgreSQL cannot replace a view when the new SELECT removes or reorders
-- existing columns. This view is read-only and has no schema dependencies.

DROP VIEW IF EXISTS public.v_dress_inventory;

CREATE VIEW public.v_dress_inventory AS
SELECT
  d.id,
  d.dress_code,
  d.name,
  d.size,
  d.color,
  d.purchase_price,
  d.rental_price,
  d.condition,
  d.status,
  d.is_active,
  d.photo_url,
  d.description,
  c.category_name,
  s.name supplier_name
FROM dresses d
LEFT JOIN dress_categories c ON c.id=d.category_id
LEFT JOIN suppliers s ON s.id=d.supplier_id
WHERE d.is_active;

ALTER TABLE business_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounting_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE document_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE dresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE dress_movements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS business_settings_read ON business_settings;
DROP POLICY IF EXISTS business_settings_admin_write ON business_settings;

CREATE POLICY business_settings_read
ON business_settings
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY business_settings_admin_write
ON business_settings
FOR ALL
TO authenticated
USING (current_app_role() = 'admin')
WITH CHECK (current_app_role() = 'admin');

DROP POLICY IF EXISTS accounting_settings_admin ON accounting_settings;

CREATE POLICY accounting_settings_admin
ON accounting_settings
FOR ALL
TO authenticated
USING (current_app_role() IN ('admin','accounting'))
WITH CHECK (current_app_role() IN ('admin','accounting'));

DROP POLICY IF EXISTS document_settings_admin ON document_settings;

CREATE POLICY document_settings_admin
ON document_settings
FOR ALL
TO authenticated
USING (current_app_role() = 'admin')
WITH CHECK (current_app_role() = 'admin');

DROP POLICY IF EXISTS system_preferences_user ON system_preferences;
DROP POLICY IF EXISTS system_preferences_admin ON system_preferences;

CREATE POLICY system_preferences_user
ON system_preferences
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY system_preferences_admin
ON system_preferences
FOR ALL
TO authenticated
USING (current_app_role() = 'admin')
WITH CHECK (current_app_role() = 'admin');

DROP POLICY IF EXISTS audit_logs_admin_read ON audit_logs;

CREATE POLICY audit_logs_admin_read
ON audit_logs
FOR SELECT
TO authenticated
USING (current_app_role() = 'admin');

DROP POLICY IF EXISTS app_users_self_read ON app_users;
DROP POLICY IF EXISTS app_users_admin_write ON app_users;

CREATE POLICY app_users_self_read
ON app_users
FOR SELECT
TO authenticated
USING (auth_user_id = auth.uid() OR current_app_role() = 'admin');

CREATE POLICY app_users_admin_write
ON app_users
FOR ALL
TO authenticated
USING (current_app_role() = 'admin')
WITH CHECK (current_app_role() = 'admin');

DROP POLICY IF EXISTS dresses_read ON dresses;
DROP POLICY IF EXISTS dresses_staff_write ON dresses;
DROP POLICY IF EXISTS dresses_staff_insert ON dresses;
DROP POLICY IF EXISTS dresses_staff_update ON dresses;

CREATE POLICY dresses_read
ON dresses
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY dresses_staff_insert
ON dresses
FOR INSERT
TO authenticated
WITH CHECK (current_app_role() IN ('admin','staff'));

CREATE POLICY dresses_staff_update
ON dresses
FOR UPDATE
TO authenticated
USING (current_app_role() IN ('admin','staff'))
WITH CHECK (current_app_role() IN ('admin','staff'));

DROP POLICY IF EXISTS dress_movements_read ON dress_movements;

CREATE POLICY dress_movements_read
ON dress_movements
FOR SELECT
TO authenticated
USING (true);

REVOKE DELETE ON dresses FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON dress_movements FROM authenticated;

-- Operational tables are never exposed to the public role. Authenticated users
-- can read; writes are role-gated, and accounting records are not deletable.

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'customers',
    'suppliers',
    'dress_categories',
    'expense_categories',
    'accounts',
    'rentals',
    'rental_details',
    'payments',
    'returns',
    'penalties',
    'purchases',
    'purchase_details',
    'expenses',
    'journal_entries',
    'journal_details',
    'purchase_payments',
    'expense_payments',
    'penalty_payments'
  ]
  LOOP
    EXECUTE format(
      'ALTER TABLE %I ENABLE ROW LEVEL SECURITY',
      table_name
    );

    IF NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = table_name
        AND policyname = 'authenticated_read'
    ) THEN
      EXECUTE format(
        'CREATE POLICY authenticated_read ON %I FOR SELECT TO authenticated USING (true)',
        table_name
      );
    END IF;

    IF table_name NOT IN ('accounts','journal_entries','journal_details')
      AND NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = table_name
          AND policyname = 'operational_insert'
      )
    THEN
      EXECUTE format(
        'CREATE POLICY operational_insert ON %I FOR INSERT TO authenticated WITH CHECK (current_app_role() IN (''admin'',''staff'',''accounting''))',
        table_name
      );
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = table_name
        AND policyname = 'operational_update'
    ) THEN
      EXECUTE format(
        'CREATE POLICY operational_update ON %I FOR UPDATE TO authenticated USING (current_app_role() IN (''admin'',''staff'',''accounting'')) WITH CHECK (current_app_role() IN (''admin'',''staff'',''accounting''))',
        table_name
      );
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM pg_policies
      WHERE schemaname = 'public'
        AND tablename = table_name
        AND policyname = 'admin_delete'
    ) THEN
      EXECUTE format(
        'CREATE POLICY admin_delete ON %I FOR DELETE TO authenticated USING (current_app_role() = ''admin'')',
        table_name
      );
    END IF;
  END LOOP;
END;
$$;

REVOKE DELETE ON
  rentals,
  payments,
  returns,
  penalties,
  purchases,
  purchase_details,
  expenses,
  journal_entries,
  journal_details,
  purchase_payments,
  expense_payments,
  penalty_payments
FROM authenticated;