-- Owner capital contribution: one atomic source transaction that posts to accounting.
-- Run after 12_return_penalty_integration.sql.

CREATE SEQUENCE IF NOT EXISTS capital_number_seq START WITH 1;

ALTER SEQUENCE capital_number_seq OWNED BY NONE;

CREATE TABLE IF NOT EXISTS capital_contributions(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  capital_code varchar(30) UNIQUE NOT NULL,
  contribution_date date NOT NULL,
  owner_name varchar(150) NOT NULL,
  contribution_type varchar(30) NOT NULL CHECK (contribution_type IN ('Cash','Bank Transfer','Asset')),
  cash_account_id bigint NOT NULL REFERENCES accounts(id),
  amount numeric(15,2) NOT NULL CHECK (amount > 0),
  description text,
  status varchar(20) NOT NULL DEFAULT 'Posted' CHECK (status IN ('Posted','Cancelled')),
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

SELECT setval(
  'capital_number_seq',
  coalesce(
    (
      SELECT max(substring(capital_code from 5)::bigint)
      FROM capital_contributions
      WHERE capital_code ~ '^MOD-[0-9]+$'
    ),
    0
  ) + 1,
  false
);

CREATE OR REPLACE FUNCTION assign_capital_code()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF nullif(NEW.capital_code,'') IS NULL THEN
    NEW.capital_code := 'MOD-' || lpad(nextval('capital_number_seq')::text,4,'0');
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS assign_capital_code ON capital_contributions;

CREATE TRIGGER assign_capital_code
BEFORE INSERT ON capital_contributions
FOR EACH ROW
EXECUTE FUNCTION assign_capital_code();

CREATE OR REPLACE FUNCTION post_capital_contribution_journal()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  modal_account_id bigint;
  cash_account_code varchar;
BEGIN
  IF NEW.status <> 'Posted' THEN
    RETURN NEW;
  END IF;

  SELECT id
  INTO modal_account_id
  FROM accounts
  WHERE account_code = '301'
  LIMIT 1;

  IF modal_account_id IS NULL THEN
    RAISE EXCEPTION 'Akun Modal Pemilik 301 belum dikonfigurasi';
  END IF;

  SELECT account_code
  INTO cash_account_code
  FROM accounts
  WHERE id = NEW.cash_account_id;

  IF cash_account_code IS NULL THEN
    RAISE EXCEPTION 'Akun kas/bank setoran modal tidak ditemukan';
  END IF;

  PERFORM post_two_line_journal(
    next_business_code('journal'),
    NEW.contribution_date,
    'capital',
    NEW.id,
    'Setoran modal ' || NEW.capital_code,
    cash_account_code,
    '301',
    NEW.amount
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS after_capital_contribution_journal ON capital_contributions;

CREATE TRIGGER after_capital_contribution_journal
AFTER INSERT ON capital_contributions
FOR EACH ROW
EXECUTE FUNCTION post_capital_contribution_journal();

ALTER TABLE capital_contributions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS capital_read ON capital_contributions;
DROP POLICY IF EXISTS capital_insert ON capital_contributions;
DROP POLICY IF EXISTS capital_update ON capital_contributions;

CREATE POLICY capital_read
ON capital_contributions
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY capital_insert
ON capital_contributions
FOR INSERT
TO authenticated
WITH CHECK (current_app_role() IN ('admin','accounting'));

CREATE POLICY capital_update
ON capital_contributions
FOR UPDATE
TO authenticated
USING (current_app_role() = 'admin')
WITH CHECK (current_app_role() = 'admin');

REVOKE DELETE ON capital_contributions FROM authenticated;

DROP VIEW IF EXISTS public.v_capital_contributions;

CREATE VIEW public.v_capital_contributions AS
SELECT
  c.id,
  c.capital_code,
  c.contribution_date,
  c.owner_name,
  c.contribution_type,
  c.amount,
  c.description,
  c.status,
  c.created_by,
  a.account_code,
  a.account_name
FROM capital_contributions c
JOIN accounts a ON a.id=c.cash_account_id;

GRANT SELECT ON public.v_capital_contributions TO authenticated;

DROP VIEW IF EXISTS public.v_cash_flow CASCADE;

CREATE VIEW public.v_cash_flow AS
SELECT
  je.journal_date,
  je.journal_code AS journal_number,
  je.reference_type,
  je.reference_id,
  je.description,
  CASE
    WHEN jd.debit > 0 THEN jd.debit
    ELSE 0
  END AS cash_in,
  CASE
    WHEN jd.credit > 0 THEN jd.credit
    ELSE 0
  END AS cash_out,
  CASE
    WHEN je.reference_type = 'capital' THEN 'Financing'
    ELSE 'Operating'
  END AS cash_flow_activity
FROM journal_entries je
JOIN journal_details jd ON jd.journal_id=je.id
JOIN accounts a ON a.id=jd.account_id
WHERE a.account_code IN ('101','1120');

NOTIFY pgrst, 'reload schema';