-- Add size variants without dropping or rewriting transaction history.
-- Run after 23_dress_model_merge_prepare.sql and populate only verified merges.

BEGIN;

LOCK TABLE
  public.dresses,
  public.purchase_details,
  public.rental_details,
  public.dress_movements
IN SHARE ROW EXCLUSIVE MODE;

DROP TRIGGER IF EXISTS record_dress_movement ON public.dresses;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.dress_model_merge_map source
    JOIN public.dress_model_merge_map target
      ON target.source_dress_id = source.target_dress_id
  ) THEN
    RAISE EXCEPTION 'Merge mapping tidak boleh berantai; arahkan semua source langsung ke master canonical';
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.dress_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dress_id bigint NOT NULL REFERENCES public.dresses(id) ON DELETE RESTRICT,
  size varchar(20) NOT NULL CHECK (length(trim(size)) > 0),
  normalized_size text GENERATED ALWAYS AS (upper(btrim(size))) STORED,
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity >= 0),
  available_quantity integer NOT NULL DEFAULT 0 CHECK (available_quantity >= 0),
  rented_quantity integer NOT NULL DEFAULT 0 CHECK (rented_quantity >= 0),
  unavailable_quantity integer NOT NULL DEFAULT 0 CHECK (unavailable_quantity >= 0),
  condition varchar(30) NOT NULL DEFAULT 'Good',
  status varchar(30) NOT NULL DEFAULT 'Not Available',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT dress_variants_dress_size_key UNIQUE (dress_id, size),
  CONSTRAINT dress_variants_dress_normalized_size_key UNIQUE (dress_id, normalized_size),
  CONSTRAINT dress_variants_quantity_balance_check CHECK (
    quantity = available_quantity + rented_quantity + unavailable_quantity
  )
);

LOCK TABLE public.dress_variants IN SHARE ROW EXCLUSIVE MODE;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_attribute
    WHERE attrelid = 'public.dress_variants'::regclass
      AND attname = 'color'
      AND NOT attisdropped
  ) AND NOT EXISTS (
    SELECT 1
    FROM public.dress_variants
    GROUP BY dress_id, normalized_size
    HAVING count(*) > 1
  ) THEN
    CREATE UNIQUE INDEX IF NOT EXISTS dress_variants_dress_normalized_size_backfill_uidx
      ON public.dress_variants(dress_id, normalized_size);
  END IF;
END;
$$;

ALTER TABLE public.purchase_details
  ADD COLUMN IF NOT EXISTS dress_variant_id bigint;

ALTER TABLE public.rental_details
  ADD COLUMN IF NOT EXISTS dress_variant_id bigint;

ALTER TABLE public.dress_movements
  ADD COLUMN IF NOT EXISTS dress_variant_id bigint,
  ADD COLUMN IF NOT EXISTS quantity_delta integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS available_delta integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rented_delta integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS unavailable_delta integer NOT NULL DEFAULT 0;

-- Legacy dress rows represented individual inventory units. Preserve their
-- current status as opening counts; purchase_details.quantity was not applied
-- to stock by the old flow, so it is intentionally not summed a second time.
-- Do not repeat this aggregate backfill after color-aware variants exist: it
-- would collapse separate colors and double-count already-created units.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_attribute
    WHERE attrelid = 'public.dress_variants'::regclass
      AND attname = 'color'
      AND NOT attisdropped
  ) THEN
    INSERT INTO public.dress_variants(
      dress_id,
      size,
      quantity,
      available_quantity,
      rented_quantity,
      unavailable_quantity,
      condition,
      status
    )
    WITH legacy_units AS (
      SELECT
        coalesce(mapping.target_dress_id, dress.id) AS canonical_dress_id,
        coalesce(nullif(upper(btrim(dress.size)), ''), 'UNKNOWN') AS size,
        coalesce(nullif(dress.condition, ''), 'Good') AS condition,
        coalesce(nullif(dress.status, ''), 'Available') AS status,
        coalesce(dress.is_active, true) AS is_active
      FROM public.dresses dress
      LEFT JOIN public.dress_model_merge_map mapping
        ON mapping.source_dress_id = dress.id
    ),
    grouped_units AS (
      SELECT
        canonical_dress_id,
        size,
        count(*)::integer AS quantity,
        count(*) FILTER (
          WHERE lower(status) = 'available'
            AND is_active
            AND size <> 'UNKNOWN'
        )::integer AS available_quantity,
        count(*) FILTER (
          WHERE lower(status) = 'rented'
        )::integer AS rented_quantity,
        (
          count(*)
          - count(*) FILTER (
            WHERE lower(status) = 'available'
              AND is_active
              AND size <> 'UNKNOWN'
          )
          - count(*) FILTER (
            WHERE lower(status) = 'rented'
          )
        )::integer AS unavailable_quantity,
        bool_or(lower(status) = 'laundry') AS has_laundry,
        bool_or(lower(status) = 'repair') AS has_repair,
        CASE
          WHEN count(DISTINCT condition) = 1 THEN min(condition)
          ELSE 'Mixed'
        END AS condition
      FROM legacy_units
      GROUP BY canonical_dress_id, size
    )
    SELECT
      canonical_dress_id,
      size,
      quantity,
      available_quantity,
      rented_quantity,
      unavailable_quantity,
      condition,
      CASE
        WHEN available_quantity > 0 THEN 'Available'
        WHEN rented_quantity = quantity THEN 'Rented'
        WHEN size = 'UNKNOWN' THEN 'Unknown Size'
        WHEN has_laundry THEN 'Laundry'
        WHEN has_repair THEN 'Repair'
        ELSE 'Not Available'
      END
    FROM grouped_units
    WHERE NOT EXISTS (
      SELECT 1
      FROM public.dress_variants existing
      WHERE existing.dress_id = grouped_units.canonical_dress_id
        AND existing.normalized_size = grouped_units.size
    );
  END IF;
END;
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT detail.id
    FROM public.purchase_details detail
    JOIN public.dresses legacy
      ON legacy.id = detail.dress_id
    LEFT JOIN public.dress_model_merge_map mapping
      ON mapping.source_dress_id = legacy.id
    JOIN public.dress_variants variant
      ON variant.dress_id = coalesce(mapping.target_dress_id, legacy.id)
      AND variant.normalized_size = coalesce(
        nullif(upper(btrim(legacy.size)), ''),
        'UNKNOWN'
      )
    WHERE detail.dress_variant_id IS NULL
    GROUP BY detail.id
    HAVING count(DISTINCT variant.id) > 1
  ) THEN
    RAISE EXCEPTION 'Purchase detail tanpa variant_id cocok ke beberapa warna; petakan manual sebelum menjalankan migration 24 ulang';
  END IF;

  IF EXISTS (
    SELECT detail.id
    FROM public.rental_details detail
    JOIN public.dresses legacy
      ON legacy.id = detail.dress_id
    LEFT JOIN public.dress_model_merge_map mapping
      ON mapping.source_dress_id = legacy.id
    JOIN public.dress_variants variant
      ON variant.dress_id = coalesce(mapping.target_dress_id, legacy.id)
      AND variant.normalized_size = coalesce(
        nullif(upper(btrim(legacy.size)), ''),
        'UNKNOWN'
      )
    WHERE detail.dress_variant_id IS NULL
    GROUP BY detail.id
    HAVING count(DISTINCT variant.id) > 1
  ) THEN
    RAISE EXCEPTION 'Rental detail tanpa variant_id cocok ke beberapa warna; petakan manual sebelum menjalankan migration 24 ulang';
  END IF;

  IF EXISTS (
    SELECT movement.id
    FROM public.dress_movements movement
    JOIN public.dresses legacy
      ON legacy.id = movement.dress_id
    LEFT JOIN public.dress_model_merge_map mapping
      ON mapping.source_dress_id = legacy.id
    JOIN public.dress_variants variant
      ON variant.dress_id = coalesce(mapping.target_dress_id, legacy.id)
      AND variant.normalized_size = coalesce(
        nullif(upper(btrim(legacy.size)), ''),
        'UNKNOWN'
      )
    WHERE movement.dress_variant_id IS NULL
    GROUP BY movement.id
    HAVING count(DISTINCT variant.id) > 1
  ) THEN
    RAISE EXCEPTION 'Movement tanpa variant_id cocok ke beberapa warna; rekonsiliasi histori sebelum menjalankan migration 24 ulang';
  END IF;
END;
$$;

UPDATE public.purchase_details detail
SET dress_variant_id = variant.id
FROM public.dresses legacy
LEFT JOIN public.dress_model_merge_map mapping
  ON mapping.source_dress_id = legacy.id
JOIN public.dress_variants variant
  ON variant.dress_id = coalesce(mapping.target_dress_id, legacy.id)
  AND variant.normalized_size = coalesce(
    nullif(upper(btrim(legacy.size)), ''),
    'UNKNOWN'
  )
WHERE detail.dress_variant_id IS NULL
  AND detail.dress_id = legacy.id;

UPDATE public.rental_details detail
SET dress_variant_id = variant.id
FROM public.dresses legacy
LEFT JOIN public.dress_model_merge_map mapping
  ON mapping.source_dress_id = legacy.id
JOIN public.dress_variants variant
  ON variant.dress_id = coalesce(mapping.target_dress_id, legacy.id)
  AND variant.normalized_size = coalesce(
    nullif(upper(btrim(legacy.size)), ''),
    'UNKNOWN'
  )
WHERE detail.dress_variant_id IS NULL
  AND detail.dress_id = legacy.id;

UPDATE public.dress_movements movement
SET dress_variant_id = variant.id
FROM public.dresses legacy
LEFT JOIN public.dress_model_merge_map mapping
  ON mapping.source_dress_id = legacy.id
JOIN public.dress_variants variant
  ON variant.dress_id = coalesce(mapping.target_dress_id, legacy.id)
  AND variant.normalized_size = coalesce(
    nullif(upper(btrim(legacy.size)), ''),
    'UNKNOWN'
  )
WHERE movement.dress_variant_id IS NULL
  AND movement.dress_id = legacy.id;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.rental_details
    WHERE dress_variant_id IS NULL
  ) THEN
    RAISE EXCEPTION 'Ada rental_detail tanpa varian yang dapat dipetakan; periksa dress_id dan data master';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.dress_movements
    WHERE dress_variant_id IS NULL
  ) THEN
    RAISE EXCEPTION 'Ada dress_movement tanpa varian yang dapat dipetakan; periksa dress_id dan data master';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.purchase_details
    WHERE quantity IS NULL OR quantity <= 0
  ) THEN
    RAISE EXCEPTION 'Ada purchase_detail dengan quantity tidak valid; perbaiki sebelum migration';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.rental_details
    WHERE quantity IS NULL OR quantity <= 0
  ) THEN
    RAISE EXCEPTION 'Ada rental_detail dengan quantity tidak valid; perbaiki sebelum migration';
  END IF;
END;
$$;

UPDATE public.purchase_details detail
SET dress_id = mapping.target_dress_id
FROM public.dress_model_merge_map mapping
WHERE detail.dress_id = mapping.source_dress_id;

UPDATE public.rental_details detail
SET dress_id = mapping.target_dress_id
FROM public.dress_model_merge_map mapping
WHERE detail.dress_id = mapping.source_dress_id;

UPDATE public.dress_movements movement
SET dress_id = mapping.target_dress_id
FROM public.dress_model_merge_map mapping
WHERE movement.dress_id = mapping.source_dress_id;

UPDATE public.dresses source
SET is_active = false
FROM public.dress_model_merge_map mapping
WHERE source.id = mapping.source_dress_id;

CREATE UNIQUE INDEX IF NOT EXISTS dresses_active_model_identity_key
ON public.dresses (
  lower(btrim(name)),
  coalesce(category_id, 0),
  lower(btrim(coalesce(color, '')))
)
WHERE is_active;

ALTER TABLE public.rental_details
  ALTER COLUMN dress_variant_id SET NOT NULL;

ALTER TABLE public.dress_movements
  ALTER COLUMN dress_variant_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.purchase_details'::regclass
      AND conname = 'purchase_details_quantity_positive'
  ) THEN
    ALTER TABLE public.purchase_details
      ADD CONSTRAINT purchase_details_quantity_positive
      CHECK (quantity > 0) NOT VALID;
  END IF;
END;
$$;

ALTER TABLE public.purchase_details
  VALIDATE CONSTRAINT purchase_details_quantity_positive;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.rental_details'::regclass
      AND conname = 'rental_details_quantity_positive'
  ) THEN
    ALTER TABLE public.rental_details
      ADD CONSTRAINT rental_details_quantity_positive
      CHECK (quantity > 0) NOT VALID;
  END IF;
END;
$$;

ALTER TABLE public.rental_details
  VALIDATE CONSTRAINT rental_details_quantity_positive;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'purchase_details_variant_fkey'
  ) THEN
    ALTER TABLE public.purchase_details
      ADD CONSTRAINT purchase_details_variant_fkey
      FOREIGN KEY (dress_variant_id)
      REFERENCES public.dress_variants(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'rental_details_variant_fkey'
  ) THEN
    ALTER TABLE public.rental_details
      ADD CONSTRAINT rental_details_variant_fkey
      FOREIGN KEY (dress_variant_id)
      REFERENCES public.dress_variants(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dress_movements_variant_fkey'
  ) THEN
    ALTER TABLE public.dress_movements
      ADD CONSTRAINT dress_movements_variant_fkey
      FOREIGN KEY (dress_variant_id)
      REFERENCES public.dress_variants(id)
      ON DELETE RESTRICT;
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_dress_variants_dress
  ON public.dress_variants(dress_id);

CREATE INDEX IF NOT EXISTS idx_purchase_details_variant
  ON public.purchase_details(dress_variant_id);

CREATE INDEX IF NOT EXISTS idx_rental_details_variant
  ON public.rental_details(dress_variant_id);

CREATE INDEX IF NOT EXISTS idx_dress_movements_variant_date
  ON public.dress_movements(dress_variant_id, movement_date DESC);

INSERT INTO public.dress_movements(
  dress_id,
  dress_variant_id,
  movement_type,
  reference_code,
  status_before,
  status_after,
  quantity_delta,
  available_delta,
  rented_delta,
  unavailable_delta,
  description
)
SELECT
  variant.dress_id,
  variant.id,
  'MIGRATION_OPENING',
  'MIGRATION-24',
  NULL,
  variant.status,
  variant.quantity,
  variant.available_quantity,
  variant.rented_quantity,
  variant.unavailable_quantity,
  'Saldo awal varian dari migrasi inventory per ukuran'
FROM public.dress_variants variant
WHERE variant.quantity > 0
  AND NOT EXISTS (
    SELECT 1
    FROM public.dress_movements movement
    WHERE movement.dress_variant_id = variant.id
      AND movement.movement_type = 'MIGRATION_OPENING'
      AND movement.reference_code = 'MIGRATION-24'
  );

ALTER TABLE public.dress_variants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS dress_variants_authenticated_read
ON public.dress_variants;

CREATE POLICY dress_variants_authenticated_read
ON public.dress_variants
FOR SELECT
TO authenticated
USING (true);

REVOKE ALL
ON public.dress_variants
FROM PUBLIC, anon, authenticated;

GRANT SELECT
ON public.dress_variants
TO authenticated;

REVOKE INSERT, UPDATE, DELETE
ON public.purchase_details, public.rental_details
FROM authenticated;

COMMIT;

NOTIFY pgrst, 'reload schema';