-- Add physical unit identity without replacing the existing model/variant
-- tables or changing purchase, rental, return, or accounting history.
-- Run after 31_purchase_payable_integrity.sql during an inventory write pause.

BEGIN;

LOCK TABLE
  public.dress_variants,
  public.rental_details,
  public.dress_movements,
  public.returns
IN SHARE ROW EXCLUSIVE MODE;

CREATE SEQUENCE IF NOT EXISTS public.dress_unit_number_seq START WITH 1;

CREATE TABLE IF NOT EXISTS public.dress_units (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variant_id bigint NOT NULL REFERENCES public.dress_variants(id) ON DELETE RESTRICT,
  unit_code varchar(40) NOT NULL UNIQUE,
  status varchar(30) NOT NULL CHECK (
    status IN (
      'Available',
      'Rented',
      'Laundry',
      'Repair',
      'Not Available',
      'Unclassified'
    )
  ),
  condition varchar(30) NOT NULL DEFAULT 'Good',
  notes text,
  legacy_generated boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.rental_details
  ADD COLUMN IF NOT EXISTS unit_id bigint;

ALTER TABLE public.returns
  ADD COLUMN IF NOT EXISTS unit_id bigint;

ALTER TABLE public.dress_movements
  ADD COLUMN IF NOT EXISTS unit_id bigint,
  ADD COLUMN IF NOT EXISTS notes text;

UPDATE public.dress_movements
SET notes = description
WHERE notes IS NULL
  AND description IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.rental_details'::regclass
      AND conname = 'rental_details_unit_fkey'
  ) THEN
    ALTER TABLE public.rental_details
      ADD CONSTRAINT rental_details_unit_fkey
      FOREIGN KEY (unit_id)
      REFERENCES public.dress_units(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.returns'::regclass
      AND conname = 'returns_unit_fkey'
  ) THEN
    ALTER TABLE public.returns
      ADD CONSTRAINT returns_unit_fkey
      FOREIGN KEY (unit_id)
      REFERENCES public.dress_units(id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.dress_movements'::regclass
      AND conname = 'dress_movements_unit_fkey'
  ) THEN
    ALTER TABLE public.dress_movements
      ADD CONSTRAINT dress_movements_unit_fkey
      FOREIGN KEY (unit_id)
      REFERENCES public.dress_units(id)
      ON DELETE RESTRICT;
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_dress_units_variant_status
  ON public.dress_units(variant_id, status, id);

CREATE INDEX IF NOT EXISTS idx_rental_details_unit
  ON public.rental_details(unit_id);

CREATE INDEX IF NOT EXISTS idx_dress_movements_unit_date
  ON public.dress_movements(unit_id, movement_date DESC);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.dress_variants variant
    WHERE variant.quantity <> variant.available_quantity
      + variant.rented_quantity
      + variant.unavailable_quantity
  ) THEN
    RAISE EXCEPTION 'Counter dress_variants tidak seimbang; rekonsiliasi sebelum membuat dress_units';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.rental_details detail
    JOIN public.rentals rental
      ON rental.id = detail.rental_id
    LEFT JOIN public.returns returned
      ON returned.rental_id = rental.id
    WHERE detail.unit_id IS NULL
      AND detail.quantity <> 1
      AND returned.id IS NULL
      AND coalesce(rental.rental_status, rental.status) NOT IN (
        'Cancelled',
        'Completed',
        'Returned'
      )
      AND rental.status NOT IN ('Cancelled', 'Completed')
  ) THEN
    RAISE EXCEPTION 'Rental aktif dengan quantity bukan satu tidak dapat dipetakan ke satu unit; pecah detail secara terkontrol sebelum migration';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.rental_details detail
    JOIN public.rentals rental
      ON rental.id = detail.rental_id
    LEFT JOIN public.returns returned
      ON returned.rental_id = rental.id
    JOIN public.dress_variants variant
      ON variant.id = detail.dress_variant_id
    WHERE detail.unit_id IS NULL
      AND returned.id IS NULL
      AND coalesce(rental.rental_status, rental.status) NOT IN (
        'Cancelled',
        'Completed',
        'Returned'
      )
      AND rental.status NOT IN ('Cancelled', 'Completed')
    GROUP BY variant.id, variant.rented_quantity
    HAVING count(*) <> variant.rented_quantity
  ) THEN
    RAISE EXCEPTION 'Jumlah rental aktif melebihi counter rented_quantity; rekonsiliasi sebelum backfill unit';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.dress_variants variant
    LEFT JOIN (
      SELECT
        detail.dress_variant_id,
        count(*)::integer AS active_rental_count
      FROM public.rental_details detail
      JOIN public.rentals rental
        ON rental.id = detail.rental_id
      LEFT JOIN public.returns returned
        ON returned.rental_id = rental.id
      WHERE returned.id IS NULL
        AND coalesce(rental.rental_status, rental.status) NOT IN (
          'Cancelled',
          'Completed',
          'Returned'
        )
        AND rental.status NOT IN ('Cancelled', 'Completed')
      GROUP BY detail.dress_variant_id
    ) active_rentals
      ON active_rentals.dress_variant_id = variant.id
    WHERE coalesce(active_rentals.active_rental_count, 0) <> variant.rented_quantity
  ) THEN
    RAISE EXCEPTION 'Counter rented_quantity tidak sama dengan rental aktif; rekonsiliasi sebelum backfill unit';
  END IF;
END;
$$;

-- Current aggregate counters are authoritative for legacy quantity. Generated
-- unit codes are internal IDs, not new dress model codes.

INSERT INTO public.dress_units(
  variant_id,
  unit_code,
  status,
  condition,
  notes,
  legacy_generated
)
SELECT
  variant.id,
  'UNIT-' || lpad(nextval('public.dress_unit_number_seq')::text, 8, '0'),
  CASE
    WHEN unit_number <= variant.available_quantity THEN 'Available'
    WHEN unit_number <= variant.available_quantity + variant.rented_quantity THEN 'Rented'
    WHEN unit_number <= variant.available_quantity
      + variant.rented_quantity
      + variant.laundry_quantity
    THEN 'Laundry'
    WHEN unit_number <= variant.available_quantity
      + variant.rented_quantity
      + variant.laundry_quantity
      + variant.repair_quantity
    THEN 'Repair'
    WHEN unit_number <= variant.available_quantity
      + variant.rented_quantity
      + variant.laundry_quantity
      + variant.repair_quantity
      + variant.not_available_quantity
    THEN 'Not Available'
    ELSE 'Unclassified'
  END,
  coalesce(variant.condition, 'Good'),
  'Generated from pre-unit aggregate inventory; verify physical label during stocktake',
  true
FROM public.dress_variants variant
CROSS JOIN LATERAL generate_series(
  1,
  variant.quantity
) AS generated(unit_number)
WHERE NOT EXISTS (
  SELECT 1
  FROM public.dress_units existing
  WHERE existing.variant_id = variant.id
);

-- Existing active detail rows each represent one checked-out unit. Assign a
-- stable generated unit so the upcoming return can identify the exact record.

WITH active_details AS (
  SELECT
    detail.id AS rental_detail_id,
    detail.dress_variant_id AS variant_id,
    row_number() OVER (
      PARTITION BY detail.dress_variant_id
      ORDER BY rental.rental_date, rental.id, detail.id
    ) AS unit_position
  FROM public.rental_details detail
  JOIN public.rentals rental
    ON rental.id = detail.rental_id
  LEFT JOIN public.returns returned
    ON returned.rental_id = rental.id
  WHERE detail.unit_id IS NULL
    AND returned.id IS NULL
    AND coalesce(rental.rental_status, rental.status) NOT IN (
      'Cancelled',
      'Completed',
      'Returned'
    )
    AND rental.status NOT IN ('Cancelled', 'Completed')
),
rented_units AS (
  SELECT
    unit.id AS unit_id,
    unit.variant_id,
    row_number() OVER (
      PARTITION BY unit.variant_id
      ORDER BY unit.id
    ) AS unit_position
  FROM public.dress_units unit
  WHERE unit.status = 'Rented'
    AND unit.legacy_generated
)
UPDATE public.rental_details detail
SET unit_id = rented_units.unit_id
FROM active_details
JOIN rented_units USING (variant_id, unit_position)
WHERE detail.id = active_details.rental_detail_id;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.dress_variants variant
    LEFT JOIN LATERAL (
      SELECT count(*)::integer AS unit_count
      FROM public.dress_units unit
      WHERE unit.variant_id = variant.id
    ) units ON true
    WHERE coalesce(units.unit_count, 0) <> variant.quantity
  ) THEN
    RAISE EXCEPTION 'Backfill dress_units tidak sama dengan quantity varian';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.rental_details detail
    JOIN public.rentals rental
      ON rental.id = detail.rental_id
    LEFT JOIN public.returns returned
      ON returned.rental_id = rental.id
    WHERE detail.unit_id IS NULL
      AND returned.id IS NULL
      AND coalesce(rental.rental_status, rental.status) NOT IN (
        'Cancelled',
        'Completed',
        'Returned'
      )
      AND rental.status NOT IN ('Cancelled', 'Completed')
  ) THEN
    RAISE EXCEPTION 'Ada rental aktif tanpa unit hasil backfill';
  END IF;
END;
$$;

ALTER TABLE public.dress_units ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS dress_units_authenticated_read
ON public.dress_units;

CREATE POLICY dress_units_authenticated_read
ON public.dress_units
FOR SELECT
TO authenticated
USING (true);

REVOKE ALL
ON public.dress_units
FROM PUBLIC, anon, authenticated;

GRANT SELECT
ON public.dress_units
TO authenticated;

REVOKE ALL
ON SEQUENCE public.dress_unit_number_seq
FROM PUBLIC, anon, authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;